### ISSUE TITLE
Problem to use functions in html

### ISSUE THREAD

**Issue by MurphyHC** [axel-zarate/js-custom-select#13]
When I try to do this the image is not displayed. The function is working well because I made  a test printing values.

<h3>Custom item template</h3>
    <p>Selected person: {{ person | json }}</p>
    <div custom-select="t as t.name for t in people | filter: { name: $searchTerm }" ng-model="person">
    <div class="pull-left" style="width: 40px">
	 <img ng-src="{{fn.getImage( t.id_image, 'product')}}" alt="Product-Image" class="imageWrapper"/>
    </div>
    <div class="pull-left">
	<strong>{{ t.name }}</strong><br />
	<span>{{t.phone }}</span>
   </div>
   <div class="clearfix"></div>
</div>

What do you thing about that?

**Comment by axel-zarate** [comment]
This is due to the fact that the `custom-select` directive creates an isolated scope (`childScope = scope.$new(true)`) to disable prototypical inheritance and thus avoid the risk of member clashes, since the directive needs to create some scope properties of its own. A workaround off the top of my head would be to add an explicit reference to the parent scope in the directive
```js
childScope.$$parent = scope;
```
and modify your binding
```html
<img ng-src="{{$$parent.fn.getImage( t.id_image, 'product')}}"  />
```
but there may be better solutions.

**Comment by MurphyHC** [comment]
Thank you, now is working !!
